### PR TITLE
templates: Fix address in --initial-advertise-peer-urls

### LINKED ISSUE #66: etcd cannot run
Towards https://github.com/giantswarm/giantswarm/issues/1388

```
Apr 25 14:40:37 ip-10-0-139-92.eu-west-1.compute.internal etcd2[13711]: --initial-cluster must include etcd0=https://0.0.0.0:2380 given --initial-advertise-peer-urls=https://0.0.0.0:2380
Apr 25 14:40:37 ip-10-0-139-92.eu-west-1.compute.internal systemd[1]: etcd2.service: Main process exited, code=exited, status=1/FAILURE
```

### PR DESCRIPTION
**Pull request by nhlfr**
--initial-cluster needs to be adjusted to --initial-advertise-peer-urls. We're now using etcd domain in both places.

Fixes #66

### CODE REVIEW

File: templates.go [hunk 1]
```diff
@@ -531,7 +531,7 @@ coreos:
       ExecStartPre=/bin/bash -c "while [ ! -f /etc/kubernetes/ssl/etcd/server-key.pem ]; do echo 'Waiting for /etc/kubernetes/ssl/etcd/server-key.pem to be written' && sleep 1; done"
       ExecStart=/usr/bin/etcd2 --advertise-client-urls=https://0.0.0.0:2379 \
                                --data-dir=/etc/kubernetes/data/etcd/ \
-                               --initial-advertise-peer-urls=https://0.0.0.0:2380 \
+                               --initial-advertise-peer-urls=https://127.0.0.1:2380 \
```
Comment (xh3b4sd) [inline templates.go]: The problem is that etcd has to listen to its domain, not on local host. It has to be available via ingress to calico within the worker nodes as well. This change is even more backwards. AFAIU the recent changes towards making etcd listening locally have just been wrong. Check https://github.com/giantswarm/k8s-vm on how it should be.

**Comment by nhlfr** [comment]
@xh3b4sd You're right. Done, PTALA.

File: templates.go [hunk 2]
```diff
@@ -529,13 +529,13 @@ coreos:
       ExecStartPre=/bin/bash -c "while [ ! -f /etc/kubernetes/ssl/etcd/server-ca.pem ]; do echo 'Waiting for /etc/kubernetes/ssl/etcd/server-ca.pem to be written' && sleep 1; done"
       ExecStartPre=/bin/bash -c "while [ ! -f /etc/kubernetes/ssl/etcd/server-crt.pem ]; do echo 'Waiting for /etc/kubernetes/ssl/etcd/server-crt.pem to be written' && sleep 1; done"
       ExecStartPre=/bin/bash -c "while [ ! -f /etc/kubernetes/ssl/etcd/server-key.pem ]; do echo 'Waiting for /etc/kubernetes/ssl/etcd/server-key.pem to be written' && sleep 1; done"
-      ExecStart=/usr/bin/etcd2 --advertise-client-urls=https://0.0.0.0:2379 \
+      ExecStart=/usr/bin/etcd2 --advertise-client-urls=https://{{ .Cluster.Etcd.Domain }}:2379 \
                                --data-dir=/etc/kubernetes/data/etcd/ \
-                               --initial-advertise-peer-urls=https://0.0.0.0:2380 \
+                               --initial-advertise-peer-urls=https://{{ .Cluster.Etcd.Domain }}:2380 \
```
Comment (rossf7) [inline templates.go]: If we need to expose 2380 externally there is still a problem. The ELB only has port 2379. If we need the server to server port we need to add it to clustertpr and expose it via the ELB in aws-operator.

Comment (nhlfr) [inline templates.go]: Good point.

What about:
- using 127.0.0.1 for --initial-advertise-peer-urls and --initial-cluster
- using domain in --advertise-client-urls
?

I will try now whether that configuration works.

Comment (xh3b4sd) [inline templates.go]: Why do we need this anyway? We only have one instance at the moment. Later we will have a cluster managed by the etcd operator, so even then we would not need to worry about it. Who has to talk to `2380` when there are no other peers? Am I missing something? So I think localhost for the peers might suffice.

Comment (nhlfr) [inline templates.go]: OK, it works :+1: 

```
# /usr/bin/etcd2 --advertise-client-urls=https://etcd.michal.aws.giantswarm.io:2379                          --data-dir=/etc/kubernetes/data/etcd/                          --initial-advertise-peer-urls=https://127.0.0.1:2380                          --listen-client-urls=https://0.0.0.0:2379                          --listen-peer-urls=https://${DEFAULT_IPV4}:2380                          --initial-cluster-token k8s-etcd-cluster                          --initial-cluster etcd0=https://127.0.0.1:2380                          --initial-cluster-state new                          --ca-file=/etc/kubernetes/ssl/etcd/server-ca.pem                          --cert-file=/etc/kubernetes/ssl/etcd/server-crt.pem                          --key-file=/etc/kubernetes/ssl/etcd/server-key.pem                          --peer-ca-file=/etc/kubernetes/ssl/etcd/server-ca.pem                          --peer-cert-file=/etc/kubernetes/ssl/etcd/server-crt.pem                          --peer-key-file=/etc/kubernetes/ssl/etcd/server-key.pem                          --peer-client-cert-auth=true                          --name etcd0
2017-04-26 15:45:36.241878 I | etcdmain: etcd Version: 2.3.7
2017-04-26 15:45:36.241938 I | etcdmain: Git SHA: fd17c91
2017-04-26 15:45:36.241942 I | etcdmain: Go Version: go1.7.5
2017-04-26 15:45:36.241946 I | etcdmain: Go OS/Arch: linux/amd64
2017-04-26 15:45:36.241950 I | etcdmain: setting maximum number of CPUs to 2, total number of available CPUs is 2
2017-04-26 15:45:36.242007 N | etcdmain: the server is already initialized as member before, starting as etcd member...
2017-04-26 15:45:36.242031 I | etcdmain: peerTLS: cert = /etc/kubernetes/ssl/etcd/server-crt.pem, key = /etc/kubernetes/ssl/etcd/server-key.pem, ca = /etc/kubernetes/ssl/etcd/server-ca.pem, trusted-ca = , client-cert-auth = true
2017-04-26 15:45:36.242701 I | etcdmain: listening for peers on https://:2380
2017-04-26 15:45:36.242722 I | etcdmain: clientTLS: cert = /etc/kubernetes/ssl/etcd/server-crt.pem, key = /etc/kubernetes/ssl/etcd/server-key.pem, ca = /etc/kubernetes/ssl/etcd/server-ca.pem, trusted-ca = , client-cert-auth = false
2017-04-26 15:45:36.243367 I | etcdmain: listening for client requests on https://0.0.0.0:2379
2017-04-26 15:45:36.244205 I | etcdserver: name = etcd0
2017-04-26 15:45:36.244224 I | etcdserver: data dir = /etc/kubernetes/data/etcd/
2017-04-26 15:45:36.244231 I | etcdserver: member dir = /etc/kubernetes/data/etcd/member
2017-04-26 15:45:36.244241 I | etcdserver: heartbeat = 100ms
2017-04-26 15:45:36.244248 I | etcdserver: election = 1000ms
2017-04-26 15:45:36.244255 I | etcdserver: snapshot count = 10000
2017-04-26 15:45:36.244273 I | etcdserver: advertise client URLs = https://etcd.michal.aws.giantswarm.io:2379
2017-04-26 15:45:36.252244 I | etcdserver: restarting member 48aea1ad8789a678 in cluster 147e329f2adb9a7d at commit index 3266
2017-04-26 15:45:36.252450 I | raft: 48aea1ad8789a678 became follower at term 4
2017-04-26 15:45:36.252469 I | raft: newRaft 48aea1ad8789a678 [peers: [], term: 4, commit: 3266, applied: 0, lastindex: 3266, lastterm: 4]
2017-04-26 15:45:36.254900 I | etcdserver: starting server... [version: 2.3.7, cluster version: to_be_decided]
2017-04-26 15:45:36.255088 E | etcdmain: failed to notify systemd for readiness: No socket
2017-04-26 15:45:36.255102 E | etcdmain: forgot to set Type=notify in systemd service file?
2017-04-26 15:45:36.255611 N | etcdserver: added local member 48aea1ad8789a678 [https://0.0.0.0:2380] to cluster 147e329f2adb9a7d
2017-04-26 15:45:36.255680 N | etcdserver: set the initial cluster version to 2.3
2017-04-26 15:45:37.553903 I | raft: 48aea1ad8789a678 is starting a new election at term 4
2017-04-26 15:45:37.554094 I | raft: 48aea1ad8789a678 became candidate at term 5
2017-04-26 15:45:37.554194 I | raft: 48aea1ad8789a678 received vote from 48aea1ad8789a678 at term 5
2017-04-26 15:45:37.554285 I | raft: 48aea1ad8789a678 became leader at term 5
2017-04-26 15:45:37.554355 I | raft: raft.node: 48aea1ad8789a678 elected leader 48aea1ad8789a678 at term 5
2017-04-26 15:45:37.556721 I | etcdserver: published {Name:etcd0 ClientURLs:[https://etcd.michal.aws.giantswarm.io:2379]} to cluster 147e329f2adb9a7d
```

So, if you agree with that approach, I will make a change.

Comment (nhlfr) [inline templates.go]: @xh3b4sd exactly, I agree, that's why I'm proposing to use localhost for initial cluster/peer.

Comment (xh3b4sd) [inline templates.go]: Then lets go with this.

Comment (nhlfr) [inline templates.go]: Done
